# Generated by Django 5.1.4 on 2024-12-25 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='descripcion',
        ),
    ]
