# Generated by Django 5.1.4 on 2024-12-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0006_venta_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(default='productos/defecto.jpg', upload_to='productos/'),
        ),
    ]
