# Generated by Django 5.1.4 on 2024-12-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='productos/defecto.jpg', null=True, upload_to='productos/'),
        ),
    ]
