# Generated by Django 5.1.4 on 2024-12-27 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0008_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='rut',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
